version: '3'
services:
  mongo:
    image: 'mongo:3.4.20-xenial'
    ports:
      - '27017:27017'
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - .:/app